name: Deploy Preview

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-app-preview:
    name: Deploy app to Cloudflare in preview mode 🌥
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/actions/prepare
      - run: pnpm --filter ./app run build
      - uses: ./.github/workflows/actions/sync-assets-to-r2
        with:
          r2_access_key_id: ${{ secrets.CLOUDFLARE_R2_ACCESS_KEY_ID }}
          r2_access_key_secret: ${{ secrets.CLOUDFLARE_R2_ACCESS_KEY_SECRET }}
      - run: pnpm --filter ./app run deploy:preview
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      - uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            Deployed PR preview to Cloudflare. Set the following header to see your work in action:

            ```
            ScoreKeep-Internal-Preview: ${{ github.event.pull_request.head.sha}}
            ```
          comment-tag: deploy-preview-instructions-comment
          github-token: ${{ secrets.COMMENT_ON_PR_GITHUB_TOKEN }}
